Repository lowRISC/ibex, pull requests merged in 2022-03, with the labels that each got.

#1554 Fix port list in top_artya7 example
  examples/fpga/artya7/rtl/top_artya7.sv
Labels: Type:Bug

#1573 [dv,core_ibex] Fix order of 'm' and 'c' in ISA string
  dv/uvm/core_ibex/tests/core_ibex_base_test.sv
Labels: Type:Bug, Component:DV

#1589 Coverage support with Cadence Tools
  dv/uvm/core_ibex/Makefile
  dv/uvm/core_ibex/fcov/core_ibex_fcov_if.sv
  dv/uvm/core_ibex/sim.py
  dv/uvm/core_ibex/yaml/rtl_simulation.yaml
Labels: Type:Enhancement, Component:DV, Component:Tool-and-Build
