Repository lowRISC/ibex, pull requests merged in 2022-11, with the labels that each got.

#1886 [pmp] Add directed instr streams to increase PMP coverage
  dv/uvm/core_ibex/riscv_dv_extension/ibex_directed_instr_lib.sv
  dv/uvm/core_ibex/riscv_dv_extension/testlist.yaml
Labels: Type:Enhancement, Component:DV

#1899 [doc] Add RF write enable glitch detection
  doc/03_reference/security.rst
Labels: Component:Doc

#1897 [xlm] Enable access to signals without dumping waves
  dv/uvm/core_ibex/yaml/rtl_simulation.yaml
Labels: Component:DV

#1906 [dv] Don't set sync_exc_seen in Debug Mode
  dv/cosim/spike_cosim.cc
Labels: Component:DV

#1942 [rtl] Flush pipe on MSECCFG CSR write
  rtl/ibex_id_stage.sv
Labels: Type:Bug
