Repository lowRISC/ibex, pull requests merged in 2022-04, with the labels that each got.

#1606 [lint] Minor fixes
  rtl/ibex_alu.sv
  rtl/ibex_lockstep.sv
Labels: Component:RTL

#1614 Fix spurious rebuilds from dumped vars
  dv/uvm/core_ibex/Makefile
Labels: Type:Bug, Component:Tool-and-Build

#1616 Replace dump-vars line for ISS runs
  dv/uvm/core_ibex/Makefile
Labels: Type:Bug, Component:Tool-and-Build

#1624 Fix quoting in ibex_config.py
  util/ibex_config.py
Labels: Type:Bug, Component:Tool-and-Build

#1625 Avoid creating xrun.log files in core_ibex directory
  dv/uvm/core_ibex/yaml/rtl_simulation.yaml
Labels: Type:Cleanup, Component:Tool-and-Build

#1626 Factor out guts of list_tests.py
  dv/uvm/core_ibex/list_tests.py
Labels: Type:Cleanup, Component:Tool-and-Build

#1630 Simplify Makefile flow by removing sim_makefrag_gen.py
  dv/uvm/core_ibex/Makefile
  dv/uvm/core_ibex/scripts/compile-tb.py
  dv/uvm/core_ibex/scripts/ibex_cmd.py
  dv/uvm/core_ibex/scripts/run-rtl.py
  dv/uvm/core_ibex/sim_makefrag_gen.py
Labels: Type:Cleanup, Component:Tool-and-Build

#1628 Allow compiling the TB when the working directory isn't core_ibex
  dv/uvm/core_ibex/scripts/compile-tb.py
  dv/uvm/core_ibex/yaml/rtl_simulation.yaml
Labels: Type:Cleanup, Component:Tool-and-Build

#1631 Rationalize paths in core_ibex Makefile and scripts
  dv/uvm/core_ibex/Makefile
  dv/uvm/core_ibex/compare.py
  dv/uvm/core_ibex/scripts/compile-generated-test.py
  dv/uvm/core_ibex/scripts/compile-tb.py
  dv/uvm/core_ibex/scripts/run-instr-gen.py
  dv/uvm/core_ibex/scripts/run-rtl.py
  dv/uvm/core_ibex/scripts/test_run_result.py
Labels: Type:Cleanup, Component:Tool-and-Build

#1633 Don't pass --iterations to list_tests.py if not overriding it
  dv/uvm/core_ibex/Makefile
  dv/uvm/core_ibex/list_tests.py
Labels: Type:Bug, Component:Tool-and-Build
