Repository lowRISC/ibex, pull requests merged in 2022-10, with the labels that each got.

#1839 [if,pmp] Check second bit instead of third for instruction alignment
  rtl/ibex_if_stage.sv
Labels: Type:Bug

#1824 Irq fixes
  rtl/ibex_controller.sv
Labels: Type:Bug

#1816 [rtl] Change how we record debug causes
  rtl/ibex_controller.sv
Labels: Type:Bug, Type:Enhancement, Component:RTL

#1868 [fcov] PMP Coverage Enhancements
  dv/uvm/core_ibex/fcov/core_ibex_pmp_fcov_if.sv
Labels: Type:Enhancement, Component:DV

#1884 [rtl] Fix dummy instructions
  rtl/ibex_core.sv
  rtl/ibex_lockstep.sv
  rtl/ibex_register_file_ff.sv
  rtl/ibex_register_file_fpga.sv
  rtl/ibex_register_file_latch.sv
  rtl/ibex_top.sv
  rtl/ibex_wb_stage.sv
Labels: Type:Bug
