Repository lowRISC/ibex, pull requests merged in 2022-05, with the labels that each got.

#1643 Instantiate plain memory primitives for ICache when ICache scrambling is disabled
  rtl/ibex_top.sv
Labels: Type:Bug, Component:RTL

#1576 Update ISA strings from Xbitmanip to XZb*
  dv/uvm/core_ibex/scripts/scripts_lib.py
  dv/uvm/core_ibex/tests/core_ibex_base_test.sv
  examples/simple_system/ibex_simple_system.cc
Labels: Type:Enhancement, Component:DV

#1661 [core_ibex] Disable waves by default
  dv/uvm/core_ibex/Makefile
Labels: Type:Cleanup, Component:DV

#1660 Dump riscv-dv generation messages to a log file
  dv/uvm/core_ibex/scripts/run-instr-gen.py
  dv/uvm/core_ibex/scripts/scripts_lib.py
Labels: Type:Enhancement, Component:DV
